version: '3'
volumes:
  socket-volume:
services:
  postgres:
    build:
      context: postgres
    volumes:
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
      POSTGRES_DEVELOPMENT_DB: 'envizon_development'
      POSTGRES_TEST_DB: 'envizon_test'
  envizon:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    network_mode: 'host'
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/envizon
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
      POSTGRES_HOST: '/var/run/postgresql'
      SECRET_KEY_BASE: 'YOUR_SECRET_HERE_PLZ'
      RAILS_ENV: 'production'
      RAILS_FORCE_SSL: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      SSL_KEY_PATH: '.ssl/localhost.key'
      SSL_CERT_PATH: '.ssl/localhost.crt'
    entrypoint: /entrypoint.sh
